@urlDev=http://localhost:3051

### create contacts
POST {{urlDev}}/api/contacts/
Content-Type: application/json

{
    "name": "ghost 2",
    "email": "ghost2@gmail.com",
    "address": "ghost 2",
    "phone": "098765432",
    "favorite": true
}

### findAll contactss
GET {{urlDev}}/api/contacts/

### find contacts by name
GET {{urlDev}}/api/contacts/?name=asd


### find contacts by id 
GET {{urlDev}}/api/contacts/63b6bcb3989834d17e39a29

### update contacts by id
PUT {{urlDev}}/api/contacts/63b6bcb3989834d17e39a293
Content-Type: application/json

{
    "name": "ghost updated 2"

}

### delete contacts by id
DELETE {{urlDev}}/api/contacts/63b6bcb3989834d17e39a293

### deleteAll contactss
DELETE {{urlDev}}/api/contacts/

###
GET {{urlDev}}/api/contacts/favorite



